bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: D1kLEvQsKmeIsmiKq5eggTfTeeqYHFb5KpJlDa3x27gPkRKdH07J1XQIeN6dVRp61rLCZb8TQN5Pemmw/NnkqZ6Z61Ygd8fwu3BYtuCVxQdpaGGtJfSWSgLAGc7RkWzNwii4ssj5BVGeMXsl2FjxnxfWunOh8lqefmsU+KhSgj+fcOcNGNlnG/A1TOG3FZinwmN38lzgipgCgYMHlHqaQkPqop2fiF63QVzzA/jDpLJtSZ8m3qp9CPxQbF/6YH5ky5eRT2z1dI6GFqUcASuA8EGpju7p9rSixvfFaVKcY9xBUecGE31HxqizWLNDgcmh20bIfnzGkANts0YhDyFYIxIWYwSSnqNtO0iRl8iskh+D6SjPezTL3o+Pmq2L+a3dfebU9ayqVl+6+2gVbGRJpUFNiLLwpGW1qUrwEb/S33hL7mogTtAla5/lqHzbfS+SGtv1EWt/0ssWFPmuYIb94hV2FlY4HApcjekMMSvReyuaf1z5kIwQb20ZtB1+XA4hf042RXFB/LeCilh9b93CSVfSkK/Hxk+luAOYEv4urOYLPxl501LSu0fpAJtWrM9SklyNA6zLOYjDnjEPcNHCs5swBN4cQzuK02v4nTNsadm/QnzX6lVBWX/iEnYFh85LRh6PvR/eaRC4ryrnOHoePZuNlFcTUlR8UtGu6pd2Rzk=
conda_forge_output_validation: false
